name: cudbscan
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  # Core dependencies
  - python=3.9
  - cmake>=3.18
  - cuda-toolkit
  - ninja  # Faster build system alternative for CMake
  - make   # GNU Make for Unix-like platforms
  
  # Python dependencies
  - pybind11>=2.9.0
  - numpy
  - pytest  # For testing
  
  # Java dependencies
  - openjdk>=11
  - gradle  # Build tool for Java
  
  # Development tools
  - git
  - jupyterlab  # For prototyping
  - pip
  - pip:
    - -e python/  # Install the Python package in development mode