name: jcudbscan
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  # Core dependencies
  - cmake>=3.18
  - cuda-toolkit
  - ninja  # Faster build system alternative for CMake
  - make   # GNU Make for Unix-like platforms
  
  # Java-specific dependencies
  - openjdk>=11
  - gradle  # Build tool for Java
  
  # Development tools
  - git