name: pycudbscan
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  # Core dependencies
  - python=3.9
  - cmake>=3.18
  - cuda-toolkit
  - ninja  # Faster build system alternative for CMake
  
  # Python-specific dependencies
  - pybind11>=2.9.0
  - numpy
  - pytest  # For testing
  
  # Development tools
  - git
  - jupyterlab  # For prototyping
  - pip
  - pip:
    - -e .  # Install the package in development mode